NetDaemonApps.Apps.DayNightSpeakerVolumeConfig:
    DayStart: 6:30
    DayVolume: 0.9
    NightStart: 21:00
    NightVolume: 0.3
    Devices:
        - media_player.living_room_speaker
        - media_player.kitchen_speaker
        - media_player.bedroom_speaker
        - media_player.lily_s_speaker