name: Deploy via Self Hosted Runner

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  FILE_NAME: publish.zip

jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: github-runner
    #environment: home-netdaemon
    steps:
    - name: Print File/Folder Tree
      run: |
        echo ---- Working Directory Folder Tree -----
        tree ./
    - name: Download Release
      uses: robinraju/release-downloader@v1.9
      with:
        latest: true
        fileName:  ${{ env.FILE_NAME }}

    - name: Debug logs
      run: |
        echo ---- Working Directory Folder Tree -----
        tree ./

