name: Deploy via Self Hosted Runner

on:
  workflow_run:
    workflows: ["Build Test Publish"]
    types:
      - completed

env:
  FILE_NAME: publish.zip

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: home-local-runner
    steps:
    - name: Download Release
      id: download-pub
      uses: robinraju/release-downloader@v1.9
      with:
        latest: true
        fileName:  ${{ env.FILE_NAME }}
    - name: Unpack and copy to target
      run: |
        echo ${{steps.download-pub.outputs.tag_name}}
        echo ${{ fromJson(steps.download-pub.outputs.downloaded_files)[0] }}

        echo "Building file directory"
        mkdir ~/${{steps.download-pub.outputs.tag_name}}
        mv -f ./${{ env.FILE_NAME }} ~/${{steps.download-pub.outputs.tag_name}}/
        
        echo "Unpacking"
        unzip  ~/${{steps.download-pub.outputs.tag_name}}/${{ env.FILE_NAME }} ~/${{steps.download-pub.outputs.tag_name}}/extracted

        echo "Copying the published artifact to server"
        scp -r ~/${{steps.download-pub.outputs.tag_name}}/extracted/* ${{secrets.AUTOMATION_SERVER_CONN}}:/docker/appdata/netdaemon 

