name: Deploy via Self Hosted Runner

on:
  workflow_run:
    workflows: ["Build Test Publish"]
    types:
      - completed

env:
  FILE_NAME: publish.zip

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: home-local-runner
    steps:
    - name: Download Release
      id: download-pub
      uses: robinraju/release-downloader@v1.9
      with:
        latest: true
        fileName:  ${{ env.FILE_NAME }}
    - name: Debug logs
      run: |
        echo ${{steps.download-pub.outputs.tag_name}}
        echo ${{ fromJson(steps.download-pub.outputs.downloaded_files)[0] }}

        echo "Building file directory"
        rm -r ~/${{steps.download-pub.outputs.tag_name}}
        mkdir ~/${{steps.download-pub.outputs.tag_name}}
        mv -f ./${{ env.FILE_NAME }} ~/${{steps.download-pub.outputs.tag_name}}/  

        echo "Copying the published artifact to server"
        scp ~/${{steps.download-pub.outputs.tag_name}}/${{ env.FILE_NAME }} ${{secrets.AUTOMATION_SERVER_CONN}}:/docker/appdata/netdaemon 
        
        echo "Unpacking and reloading netdaemon"
        ssh -t ${{secrets.AUTOMATION_SERVER_CONN}} unzip -o /docker/appdata/netdaemon/${{ env.FILE_NAME }}
        ssh -t ${{secrets.AUTOMATION_SERVER_CONN}} docker restart netdaemon4
