name: Deploy via Self Hosted Runner

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  ARTIFACT_NAME: netdaemon-publish

jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: github-runner
    #environment: home-netdaemon
    steps:
    - name: Print File/Folder Tree
      run: |
        echo ---- Working Directory Folder Tree -----
        tree $PUBLISH_DIRECTORY
    - name: Download Publish Files
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}

