name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    PUBLISH_DIRECTORY: ./bin/Release/net8.0/publish

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    # - name: Git Version
    #   id: version
    #   uses: codacy/git-version@2.7.1    
    - name: Restore dependencies
      run: dotnet restore  
    - name: Test
      run: dotnet test --no-build --verbosity normal    
    - name: Publish
      run: dotnet publish -c release
    - name: Print File/Folder Tree
      run: |
        echo ---- Working Directory -----
        tree -d ./
        echo ---- Publish Directory -----
        tree $PUBLISH_DIRECTORY
    - name: Archive Build Files
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-publish-files
        path: ${$PUBLISH_DIRECTORY}

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build_and_test
  #   steps:
  #   - name: Zip Folder
  #     run: |
  #       ls ./
  #       cd /home/runner/work/NetDaemon/NetDaemon/bin/Release/net8.0/publish
  #       zip -r ./publish.zip ./*
  #   - name: Release
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       tag_name: ${{ steps.version.outputs.version }}
  #       files: /home/runner/work/NetDaemon/NetDaemon/bin/Release/net8.0/publish/publish.zip
