name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    PUBLISH_DIRECTORY: ./NetDaemonApps/bin/Release/net8.0/publish
    ARTIFACT_NAME: netdaemon-publish
    PUBLISH_FILENAME: publish.zip

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  
    - name: Restore dependencies
      run: dotnet restore  
    - name: Test
      run: dotnet test --verbosity normal    
    - name: Publish
      run: dotnet publish -c release
    - name: Get Next Version Number
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Zip Publish Files
      run: |
        gh release create ${{ steps.version.outputs.version }}
        zip -r ./${{ env.PUBLISH_FILENAME }} ./*
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: ./${{ env.PUBLISH_FILENAME }}
