name: Build Test Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    PUBLISH_DIRECTORY: ./NetDaemonApps/bin/Release/net8.0/publish
    ARTIFACT_NAME: netdaemon-publish
    PUBLISH_NAME: netdaemon-deploy
    PUBLISH_FILENAME: publish.zip

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Get Next Version Number
      id: version
      uses: codacy/git-version@2.7.1
      with:
        release-branch: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  
    - name: Restore dependencies
      run: dotnet restore  
    - name: Test
      run: dotnet test --verbosity normal    
    - name: Publish
      run: dotnet publish -c release
    - name: Print File/Folder Tree
      run: |
        echo ---- Working Directory Folder Tree -----
        tree -d ./
        echo ---- Publish Directory Files -----
        tree $PUBLISH_DIRECTORY
    - name: Archive Build Files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./
    - name: Zip Publish Files
      run: |
        zip -r ./${{ env.PUBLISH_FILENAME }} ${{ env.PUBLISH_DIRECTORY }}/*
    # - name: Upload to GitHub Releases
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     tag_name: ${{ steps.version.outputs.version }}
    #     files: ./${{ env.PUBLISH_FILENAME }}
