name: Build Test Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    PUBLISH_DIRECTORY: ./NetDaemonApps/bin/Release/net8.0/publish
    ARTIFACT_NAME: netdaemon-publish
    PUBLISH_NAME: netdaemon-deploy
    PUBLISH_FILENAME: publish.zip

jobs:
  
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.3.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  
    - name: Restore dependencies
      run: dotnet restore  
    - name: Test
      run: dotnet test --verbosity normal    
    - name: Publish
      run: dotnet publish -c release 
    - name: Archive Build Files
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./
    - name: Zip Publish Files
      run: |
        cd ${{ env.PUBLISH_DIRECTORY }}
        zip -r ${{ env.PUBLISH_FILENAME }} ./*
    - name: Print File/Folder Tree
      run: |
        echo ---- Versioning -----
        echo version ${{ steps.version.outputs.version_tag }}
        echo ---- Working Directory Folder Tree -----
        tree ./
    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version_tag }}
        files: ./${{ env.PUBLISH_DIRECTORY }}/${{ env.PUBLISH_FILENAME }}
